# Generated by Django 5.0.6 on 2024-06-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_discription_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
